CREATE TABLE users(
username VARCHAR(200) UNIQUE,
password VARCHAR(200),
id BIGSERIAL PRIMARY KEY,
first_name TEXT NOT NULL,
last_name TEXT NOT NULL
);

CREATE TABLE budget(
id BIGSERIAL PRIMARY KEY,
user_id BIGSERIAL NOT NULL REFERENCES users(id),
name VARCHAR(200) NOT NULL
);

CREATE TABLE budget_item(
id BIGSERIAL PRIMARY KEY,
budget_id BIGSERIAL NOT NULL REFERENCES budget(id),
amount NUMERIC NOT NULL,
name VARCHAR(200) NOT NULL,
type VARCHAR(200) NOT NULL
);

CREATE TABLE budget_item_update(
id BIGSERIAL PRIMARY KEY,
budget_item_id BIGSERIAL NOT NULL REFERENCES budget_item(id),
month SMALLINT NOT NULL,
year SMALLINT NOT NULL,
name TEXT NOT NULL,
amount NUMERIC NOT NULL,
month_specific BOOLEAN NOT NULL
);